# Generated by Django 3.1.12 on 2025-02-01 15:56

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False, verbose_name='ラベル番号')),
                ('name', models.TextField(verbose_name='ラベル名')),
                ('type', models.TextField(verbose_name='ラベルタイプ')),
            ],
            options={
                'db_table': 'labels',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('title', models.TextField(verbose_name='タイトル')),
                ('contents', models.TextField(verbose_name='内容')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('post_no', models.TextField(primary_key=True, serialize=False, verbose_name='投稿番号')),
                ('categories', djongo.models.fields.JSONField(default=list)),
                ('tags', djongo.models.fields.JSONField(default=list)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
    ]
